version: "2"

services:
  alpine.curl:
    build: ./alpine.curl
    container_name: alpine1
#    tty: true
    volumes:
      - shared-vol:/shared
#    restart: always

  nginx:
    build: ./nginx
    volumes:
      - shared-vol:/usr/share/nginx/html/images
    ports:
      - "80:80"
#    restart: always

volumes:
  shared-vol:
  
